services:
  - type: web
    name: neuroscan
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: neuroscan-secret-key-production-2025
    healthCheckPath: /
